# 生产环境配置
# 严格遵循全局规范：安全、稳定、可观测

scanner:
  service_name: scan_pulse
  web:
    host: 0.0.0.0
    port: 8000
  zmq:
    publisher_bind: tcp://0.0.0.0:5555
    reply_bind: tcp://0.0.0.0:5558

redis:
  host: redis
  port: 6379
  db: 0

zmq:
  publisher_port: 5555
  subscriber_port: 5556

rules:
  three_high:
    enabled: true
    min_turnover: 10000000     # 最低成交额
    min_amplitude: 0.02        # 最小振幅
    min_volume_ratio: 1.5      # 最小量比
  black_horse:
    enabled: true
    min_rise: 0.03             # 最小涨幅
    max_drawdown: 0.02         # 最大回撤

logging:
  level: INFO            # 标准日志级别
  console:
    enabled: false       # 生产环境不输出到控制台
    colorize: false
  file:
    enabled: true
    path: logs/scanner_prod.log

api_factory:
  url: "http://apiforge:8000"