# Prometheus 配置文件
# 用于监控市场微结构仿真引擎 (MMS)

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mms-monitor'
    environment: 'production'

# 规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # MMS 主服务监控
  - job_name: 'mms-main'
    static_configs:
      - targets: ['mms-main:50051']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # MMS 工作进程监控
  - job_name: 'mms-workers'
    static_configs:
      - targets:
        - 'mms-worker-1:50052'
        - 'mms-worker-2:50053'
        - 'mms-worker-3:50054'
        - 'mms-worker-4:50055'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Redis 监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # 系统监控 (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker 容器监控 (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # ZeroMQ 监控（如果有专门的导出器）
  - job_name: 'zmq-exporter'
    static_configs:
      - targets: ['zmq-exporter:9101']
    scrape_interval: 30s
    metrics_path: /metrics

# 远程写入配置（可选）
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# 远程读取配置（可选）
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"

# 存储配置
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Web 配置
web:
  console.templates: /etc/prometheus/consoles
  console.libraries: /etc/prometheus/console_libraries
  enable-lifecycle: true
  enable-admin-api: true