# 测试环境配置
# 严格按照数据隔离和环境管理规范V1.0

# 应用配置
app:
  name: "NeuroTrade Nexus - Master Control Module"
  version: "1.0.0"
  environment: "staging"
  debug: false
  log_level: "INFO"

# 数据库配置 - 测试环境隔离
database:
  type: "sqlite"
  path: "./data/staging/master_control.db"
  backup_path: "./data/staging/backups/"
  auto_backup: true
  backup_interval: 1800  # 30分钟

# Redis配置 - 测试环境隔离
redis:
  host: "localhost"
  port: 6379
  db: 1  # 测试环境使用DB1
  password: null
  max_connections: 15
  connection_timeout: 5
  key_prefix: "ntn:staging:"

# ZeroMQ配置 - 测试环境端口隔离
zeromq:
  base_port: 5655  # 测试环境基础端口
  pub_port: 5655
  sub_port: 5656
  router_port: 5657
  dealer_port: 5658
  
  # 模组端口配置
  modules:
    master_control:
      pub_port: 5655
      sub_port: 5656
      router_port: 5657
      dealer_port: 5658
    data_collection:
      pub_port: 5665
      sub_port: 5666
      router_port: 5667
      dealer_port: 5668
    signal_generation:
      pub_port: 5675
      sub_port: 5676
      router_port: 5677
      dealer_port: 5678
    execution_engine:
      pub_port: 5685
      sub_port: 5686
      router_port: 5687
      dealer_port: 5688
    risk_management:
      pub_port: 5695
      sub_port: 5696
      router_port: 5697
      dealer_port: 5698
    performance_analysis:
      pub_port: 5705
      sub_port: 5706
      router_port: 5707
      dealer_port: 5708
    market_analysis:
      pub_port: 5715
      sub_port: 5716
      router_port: 5717
      dealer_port: 5718

# API配置
api:
  host: "0.0.0.0"
  port: 8001
  prefix: "/api/v1"
  cors_origins:
    - "http://staging.neurotrade.local:3000"
    - "http://staging.neurotrade.local:5173"
  cors_credentials: true
  
# 安全配置
security:
  secret_key: "staging-secret-key-different-from-dev"
  access_token_expire_minutes: 45
  algorithm: "HS256"
  
# 日志配置
logging:
  level: "INFO"
  file: "./logs/staging/master_control.log"
  max_size: "20MB"
  backup_count: 10
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# 交易配置 - 测试环境使用模拟交易
trading:
  enabled: true
  simulation_mode: true
  paper_trading: true
  
# 风险管理配置
risk:
  max_drawdown: 0.03  # 3% - 更严格
  position_limit: 0.15  # 15% - 更保守
  daily_loss_limit: 0.02  # 2%
  circuit_breaker_enabled: true
  
# 资金管理配置
fund:
  default_mode: "balanced"
  initial_capital: 500000.0
  currency: "USD"
  
# 监控配置
monitoring:
  enabled: true
  heartbeat_interval: 20  # 秒
  health_check_interval: 30  # 秒
  metrics_collection: true
  performance_tracking: true
  
# 测试配置
testing:
  automated_tests: true
  load_testing: true
  stress_testing: true
  mock_data: false
  real_market_data: true