# Prometheus配置文件
# 监控扫描器模组性能和健康状态

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'scanner-monitor'
    environment: 'production'

# 规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # 扫描器主服务监控
  - job_name: 'scanner-main'
    static_configs:
      - targets: ['scanner:8080']  # 假设扫描器暴露metrics端点
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    metrics_path: /metrics
    # 需要redis_exporter

  # ZeroMQ监控（如果有exporter）
  - job_name: 'zeromq'
    static_configs:
      - targets: ['scanner:9091']  # ZMQ metrics端口
    scrape_interval: 15s
    metrics_path: /metrics

  # 系统监控（Node Exporter）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # 容器监控（cAdvisor）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

# 远程写入配置（可选）
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置（可选）
# remote_read:
#   - url: "http://remote-storage:9201/read"