# 生产环境配置
# 严格遵循：生产环境安全规范和性能优化

# 继承基础配置
base_config: "base.yaml"

# 生产环境标识
environment: "production"

# 严禁Mock数据
mock_data:
  enabled: false

# 生产环境数据库配置
database:
  sqlite_file: "data/prod.db"
  auto_create_tables: true
  backup_enabled: true
  backup_interval: "6 hours"
  backup_retention: "30 days"

# Redis生产配置
redis:
  db: 2  # 生产环境专用数据库
  connection_pool_size: 10
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true

# 生产环境日志配置
logging:
  level: "INFO"
  console_output: false  # 生产环境不输出到控制台
  file_output: true
  log_file: "logs/prod_crawler.log"
  error_log_file: "logs/prod_crawler_error.log"
  # 生产环境日志轮转
  rotation: "100 MB"
  retention: "90 days"

# 生产环境爬虫配置
scraper:
  # 生产环境使用标准延迟
  request_delay:
    min: 2
    max: 5
  retry_times: 3
  timeout: 30
  # 生产环境反爬策略
  proxy_pool_size: 10
  user_agent_pool_size: 20
  concurrent_requests: 5

# Telegram生产配置
telegram:
  session_name: "prod_crawler_session"
  use_mock_client: false
  connection_retries: 5
  flood_sleep_threshold: 60

# 生产环境监控配置
monitoring:
  enabled: true
  metrics_port: 8000
  health_check_port: 8001
  prometheus_metrics: true
  
# 性能优化配置
performance:
  # 数据处理批次大小
  batch_size: 100
  # 内存使用限制
  max_memory_usage: "512MB"
  # 并发处理数
  max_concurrent_tasks: 10

# 安全配置
security:
  # 数据加密
  encrypt_sensitive_data: true
  # API密钥轮换
  api_key_rotation_interval: "30 days"
  # 访问日志
  access_logging: true

# 错误处理和告警
error_handling:
  # 错误重试策略
  exponential_backoff: true
  max_retry_delay: 300  # 5分钟
  # 告警配置
  alert_on_consecutive_failures: 5
  alert_webhook_url: null  # 通过环境变量注